import os
import json
from dotenv import load_dotenv
from pathlib import Path
from groq import Groq
from tavily import TavilyClient

load_dotenv(dotenv_path=Path(__file__).parent / ".env")

MODEL = "llama3-70b-8192"

groq = Groq(api_key=os.getenv("GROQ_API_KEY"))
tavily = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))


def chat(system: str, user: str) -> str:
    response = groq.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user",   "content": user}
        ]
    )
    return response.choices[0].message.content


# ── Agent 1: Trend Researcher ────────────────────────────────────
def trend_researcher(sector: str, log=None) -> str:
    if log: log("Agent 1: Searching for trends...")

    queries = [
        f"{sector} industry trends 2025",
        f"{sector} startup funding news recent",
        f"{sector} expert forecast market outlook",
        f"{sector} technology innovation developments",
    ]

    all_results = []
    for q in queries:
        results = tavily.search(query=q, max_results=3)
        for r in results.get("results", []):
            all_results.append(f"Source: {r['url']}\n{r['content']}\n")

    raw_text = "\n---\n".join(all_results)

    research = chat(
        system="You are a senior research analyst who produces accurate, well-sourced summaries.",
        user=f"""Here are recent web search results about the {sector} industry:

{raw_text}

Summarize the key findings as structured bullet points. Focus on:
- Recent product/technology launches
- Funding rounds and M&A activity
- Regulatory changes
- Market size and growth data
- Expert predictions

Be factual and cite sources where possible."""
    )

    if log: log("Agent 1: Research complete.")
    return research


# ── Agent 2: Signal Extractor ────────────────────────────────────
def signal_extractor(sector: str, research: str, log=None) -> str:
    if log: log("Agent 2: Extracting top 5 signals...")

    signals = chat(
        system="You are a strategic analyst. Always respond with valid JSON only. No extra text.",
        user=f"""Based on this research about the {sector} industry:

{research}

Extract EXACTLY the top 5 most important trend signals.

Return ONLY this JSON:
{{
  "sector": "{sector}",
  "signals": [
    {{
      "rank": 1,
      "title": "short title max 5 words",
      "description": "one sentence description",
      "why_it_matters": "one sentence on business impact",
      "confidence": "High"
    }}
  ]
}}"""
    )

    if log: log("Agent 2: Signals extracted.")
    return signals


# ── Agent 3: Report Writer ───────────────────────────────────────
def report_writer(sector: str, research: str, signals_json: str, log=None) -> str:
    if log: log("Agent 3: Writing report...")

    report = chat(
        system="You are a senior industry analyst. Write clear, professional, executive-ready reports.",
        user=f"""Write a professional industry trend report for executives.

SECTOR: {sector}
RESEARCH: {research}
TOP 5 SIGNALS: {signals_json}

Use these exact sections:

# {sector} Industry Trend Report

## Executive Summary
## Top 5 Trend Signals
## Key Players to Watch
## Investment & Funding Highlights
## Outlook: Next 12 Months

---
*Report generated by Industry Trend Agent*"""
    )

    if log: log("Agent 3: Report complete.")
    return report


# ── Agent 4: LLM Judge ──────────────────────────────────────────
def llm_judge(sector: str, report: str, log=None) -> dict:
    if log: log("Agent 4: Evaluating report...")

    result_text = chat(
        system="You are an expert evaluator. Always respond with valid JSON only. No extra text.",
        user=f"""Evaluate this {sector} industry trend report.

Score each criterion 1 to 5:

ACCURACY: Are all claims factual and well-supported?
RELEVANCE: Are the signals specific to this sector?
ANALYTICAL DEPTH: Is there real strategic insight beyond just news?

REPORT:
{report}

Return ONLY this JSON:
{{
  "scores": {{
    "accuracy":         {{"score": 0, "reasoning": "..."}},
    "relevance":        {{"score": 0, "reasoning": "..."}},
    "analytical_depth": {{"score": 0, "reasoning": "..."}}
  }},
  "overall_score": 0,
  "summary": "one paragraph assessment",
  "top_strength": "best aspect",
  "top_improvement": "most important improvement"
}}"""
    )

    text = result_text.strip().replace("```json", "").replace("```", "").strip()

    try:
        result = json.loads(text)
    except json.JSONDecodeError:
        result = {
            "scores": {
                "accuracy":         {"score": 3, "reasoning": "Parse error."},
                "relevance":        {"score": 3, "reasoning": "Parse error."},
                "analytical_depth": {"score": 3, "reasoning": "Parse error."}
            },
            "overall_score": 3,
            "summary": "Could not parse judge response.",
            "top_strength": "N/A",
            "top_improvement": "N/A"
        }

    if log: log(f"Agent 4: Overall score = {result.get('overall_score', '?')}/5")
    return result